# Generated by Django 5.1.2 on 2024-10-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_orden', models.DateField()),
                ('documento_orden', models.CharField(max_length=50)),
                ('numero_orden', models.IntegerField()),
                ('codigo_prueba', models.CharField(max_length=20)),
                ('nombre_prueba', models.CharField(max_length=100)),
                ('resultado', models.CharField(max_length=200)),
                ('valores_referencia', models.TextField()),
                ('unidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='sexo_biologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
    ]
