# Generated by Django 5.1.2 on 2024-10-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_administrador_salud_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador_salud',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='tipo_examen',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
    ]
