# Generated by Django 5.1.2 on 2024-10-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_administrador_salud_nombre_alter_medico_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_examen',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
