# Generated by Django 5.1.2 on 2024-10-12 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_tipo_examen_descripcion'),
        ('login', '0012_ordenlaboratorios_delete_orden_result_pac'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrdenLaboratorio',
        ),
    ]
