# Generated by Django 5.1.2 on 2024-10-12 04:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0006_delete_ordenlaboratorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_identificacion', models.CharField(choices=[('TI', 'Tarjeta de Identidad'), ('CC', 'Cédula de Ciudadania'), ('CE', 'Cédula de Extranjería')], max_length=20)),
                ('numero_id', models.CharField(max_length=50, unique=True)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50)),
                ('nombre1', models.CharField(max_length=50)),
                ('nombre2', models.CharField(default='No especificado', max_length=50)),
                ('fecha_nac', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.TextField(null=True)),
                ('tel_movil', models.CharField(max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_salud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.administrador_salud')),
                ('groups', models.ManyToManyField(blank=True, related_name='persona_set', to='auth.group')),
                ('sexo_biologico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.sexo_biologico')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='persona_user_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenLaboratorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_orden', models.DateField()),
                ('documento_orden', models.CharField(max_length=50)),
                ('numero_orden', models.IntegerField()),
                ('codigo_prueba', models.CharField(max_length=20)),
                ('nombre_prueba', models.CharField(max_length=100)),
                ('resultado', models.CharField(max_length=200)),
                ('valores_referencia', models.TextField()),
                ('unidad', models.CharField(max_length=20)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.persona')),
            ],
        ),
    ]
