# Generated by Django 5.1.2 on 2024-10-12 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_persona_ordenlaboratorios'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenlaboratorios',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.medico'),
        ),
    ]
