# Generated by Django 5.1.2 on 2024-10-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_ordenlaboratorios_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenlaboratorios',
            name='name_group',
            field=models.CharField(choices=[('Hematologia', 'Hematologia'), ('Oncología', 'Oncología'), ('Cardiología', 'Cardiología'), ('Neurología', 'Neurología'), ('Pediatría', 'Pediatría'), ('Ginecología', 'Ginecología'), ('Urología', 'Urología'), ('Gastroenterología', 'Gastroenterología'), ('Oftalmología', 'Oftalmología'), ('Dermatología', 'Dermatología'), ('Psiquiatría', 'Psiquiatría')], default='Desconocida', max_length=50),
        ),
    ]
