# Generated by Django 5.1.2 on 2024-10-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_ordenlaboratorios_name_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nombre2',
            field=models.CharField(default='', max_length=50),
        ),
    ]
