# Generated by Django 5.1.2 on 2024-10-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_ordenlaboratorios_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nombre2',
            field=models.CharField(db_default='None', max_length=50),
        ),
    ]
