# Generated by Django 5.1.2 on 2024-10-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_persona_id_sexobiologico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nombre2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
