# Generated by Django 5.1.2 on 2024-10-11 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_tipo_examen_descripcion'),
        ('login', '0003_alter_persona_nombre2'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='administradora_salud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.administrador_salud'),
        ),
    ]
