# Generated by Django 5.1.2 on 2024-10-11 23:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('login', '0004_persona_administradora_salud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='administradora_salud',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='id_sexo_biologico',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='tel_movil',
        ),
        migrations.AddField(
            model_name='persona',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='persona_set', to='auth.group'),
        ),
        migrations.AddField(
            model_name='persona',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persona',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='persona',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='persona',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='persona_user_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='numero_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
