# Generated by Django 5.1.2 on 2024-10-11 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_tipo_examen_descripcion'),
        ('login', '0005_remove_persona_administradora_salud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='admin_salud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.administrador_salud'),
        ),
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_sexo_biologico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.sexo_biologico'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tel_movil',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
