# Generated by Django 5.1.2 on 2024-10-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_persona_admin_salud_persona_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
