# Generated by Django 5.1.2 on 2024-10-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_persona_nombre2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
