# Generated by Django 5.1.2 on 2024-10-12 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_persona_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='id_sexo_biologico',
            new_name='sexo_biologico',
        ),
    ]
