# Generated by Django 5.1.2 on 2024-10-12 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_ordenlaboratorios_delete_orden_result_pac'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
