# Generated by Django 5.1.2 on 2024-10-12 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_delete_persona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrdenLaboratorios',
        ),
    ]
